spring.application.name=course-registration
server.port=9090

spring.datasource.url=jdbc:h2:file:./data/course_registration_exam_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.error.include-message=always

app.page-size=5
app.google.client-id=${GOOGLE_CLIENT_ID:demo-google-client-id}
app.google.client-secret=${GOOGLE_CLIENT_SECRET:demo-google-client-secret}
